import type {SystemMapDataset} from "@eCommerceModule/clients/panel/private/systemMap/systemMap.types.ts";

/**
 * Hand-curated System Map for the eCommerceMarketplace module.
 * Includes escrow bridge models (owned by eCommerce) that marketplace orders depend on.
 */

export const MARKETPLACE_SYSTEM_MAP: SystemMapDataset = {
    clusters: ["marketplace", "escrow", "shared"],
    nodes: [
        {
            id: "Category",
            label: "Category",
            cluster: "shared",
            module: "shared",
            description: "Shared taxonomy (eCommerce) used by listings and task requests.",
            keyFields: ["name", "slug", "parent", "path"],
            apiPath: "/api/eCommerceMarketplace/listingCategory",
            panelRoute: "/eCommerce/listingcategories",
            position: {x: 280, y: 40},
        },
        {
            id: "ProviderProfile",
            label: "ProviderProfile",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description:
                "Seller/provider identity with skills, portfolio, and Stripe Connect account flags.",
            keyFields: ["user", "company", "skills", "bio", "stripeAccountId", "chargesEnabled"],
            apiPath: "/api/eCommerceMarketplace/providerProfile",
            panelRoute: "/eCommerce/providerprofile",
            actions: ["createAccountLink", "refreshAccountStatus"],
            position: {x: 40, y: 40},
        },
        {
            id: "ProviderAvailability",
            label: "ProviderAvailability",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Schedule windows when a provider can take bookings.",
            keyFields: ["provider", "windows", "timezone"],
            apiPath: "/api/eCommerceMarketplace/providerAvailability",
            panelRoute: "/eCommerce/provideravailability",
            position: {x: 40, y: 180},
        },
        {
            id: "Listing",
            label: "Listing",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Service or offering published by a provider under a category.",
            keyFields: ["title", "category", "provider", "price", "pricingType", "deliveryDays", "status"],
            apiPath: "/api/eCommerceMarketplace/listing",
            panelRoute: "/eCommerce/listings",
            position: {x: 280, y: 180},
        },
        {
            id: "ListingPackage",
            label: "ListingPackage",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Tiered package (Basic / Standard / Premium) for a listing.",
            keyFields: ["listing", "name", "price", "deliveryDays"],
            apiPath: "/api/eCommerceMarketplace/listingPackage",
            panelRoute: "/eCommerce/listingpackages",
            position: {x: 520, y: 100},
        },
        {
            id: "ListingAddOn",
            label: "ListingAddOn",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Optional paid extras attachable to a listing purchase.",
            keyFields: ["listing", "title", "price", "deliveryDays"],
            apiPath: "/api/eCommerceMarketplace/listingAddOn",
            panelRoute: "/eCommerce/listingaddons",
            position: {x: 520, y: 240},
        },
        {
            id: "ListingFlag",
            label: "ListingFlag",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Moderation report against a listing.",
            keyFields: ["listing", "reason", "status"],
            apiPath: "/api/eCommerceMarketplace/listingFlag",
            panelRoute: "/eCommerce/listingflags",
            position: {x: 520, y: 380},
        },
        {
            id: "Promotion",
            label: "Promotion",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Featured / sponsored listing promotion lifecycle.",
            keyFields: ["listings", "type", "status", "startsAt", "endsAt"],
            apiPath: "/api/eCommerceMarketplace/promotion",
            panelRoute: "/eCommerce/promotions",
            position: {x: 520, y: 520},
        },
        {
            id: "TaskRequest",
            label: "TaskRequest",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Buyer posts a job with budget; providers bid; winner becomes an order.",
            keyFields: ["requester", "title", "budgetMin", "budgetMax", "category", "status"],
            apiPath: "/api/eCommerceMarketplace/taskRequest",
            panelRoute: "/eCommerce/taskrequests",
            actions: ["close", "reopen", "notifyAll"],
            position: {x: 40, y: 360},
        },
        {
            id: "Bid",
            label: "Bid",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Provider proposal on a task request.",
            keyFields: ["taskRequest", "bidder", "amount", "proposal", "deliveryDays", "status"],
            apiPath: "/api/eCommerceMarketplace/bid",
            panelRoute: "/eCommerce/bids",
            position: {x: 40, y: 500},
        },
        {
            id: "MarketplaceOrder",
            label: "Order",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description:
                "Hub for marketplace work — from listing purchase or accepted bid; drives escrow, delivery, disputes.",
            keyFields: ["listing?", "taskRequest?", "bid?", "customer", "provider", "amount", "status"],
            apiPath: "/api/eCommerceMarketplace/order",
            panelRoute: "/eCommerce/orders",
            actions: [
                "createFromListing",
                "accept",
                "start",
                "submitDelivery",
                "requestRevision",
                "acceptDelivery",
                "raiseDispute",
                "cancel",
                "extend",
            ],
            position: {x: 280, y: 520},
        },
        {
            id: "Booking",
            label: "Booking",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Time-boxed appointment linked to a marketplace order.",
            keyFields: ["order", "provider", "startAt", "endAt", "timezone"],
            apiPath: "/api/eCommerceMarketplace/booking",
            panelRoute: "/eCommerce/bookings",
            position: {x: 40, y: 660},
        },
        {
            id: "Dispute",
            label: "Dispute",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Conflict on a marketplace order; can trigger escrow refund.",
            keyFields: ["order", "initiator", "reason", "status", "resolution"],
            apiPath: "/api/eCommerceMarketplace/dispute",
            panelRoute: "/eCommerce/disputes",
            position: {x: 40, y: 800},
        },
        {
            id: "Review",
            label: "Review",
            cluster: "marketplace",
            module: "eCommerceMarketplace",
            description: "Rating for a completed marketplace order / listing.",
            keyFields: ["order", "listing", "rating", "body"],
            apiPath: "/api/eCommerceMarketplace/review",
            panelRoute: "/eCommerce/reviews",
            position: {x: 280, y: 800},
        },
        {
            id: "EscrowTransaction",
            label: "EscrowTransaction",
            cluster: "escrow",
            module: "eCommerce",
            description:
                "Bridge into eCommerce: hold → release+10% fee | refund. Schema and APIs live in eCommerce.",
            keyFields: ["order", "type", "amount", "gatewayIds", "status"],
            apiPath: "/api/finance/escrowTransaction",
            panelRoute: "/finance/escrowdashboard",
            actions: ["createEscrowHold", "createEscrowReleaseAndFee", "refund"],
            position: {x: 560, y: 520},
        },
        {
            id: "OrderMilestone",
            label: "OrderMilestone",
            cluster: "escrow",
            module: "eCommerce",
            description: "Milestone escrow steps (eCommerce schema) for marketplace orders.",
            keyFields: ["order", "title", "amount", "status", "dueAt"],
            apiPath: "/api/eCommerceMarketplace/orderMilestone",
            position: {x: 800, y: 420},
        },
        {
            id: "OrderDelivery",
            label: "OrderDelivery",
            cluster: "escrow",
            module: "eCommerce",
            description: "Provider delivery submission (eCommerce schema) against marketplace Order.",
            keyFields: ["order", "files", "message", "status"],
            apiPath: "/api/eCommerceMarketplace/orderDelivery",
            position: {x: 800, y: 560},
        },
        {
            id: "OrderRevision",
            label: "OrderRevision",
            cluster: "escrow",
            module: "eCommerce",
            description: "Buyer revision requests (max 3) before accepting delivery.",
            keyFields: ["order", "message", "status"],
            apiPath: "/api/eCommerceMarketplace/orderRevision",
            position: {x: 800, y: 700},
        },
    ],
    edges: [
        {id: "e-list-prov", source: "Listing", target: "ProviderProfile", label: "by"},
        {id: "e-list-cat", source: "Listing", target: "Category", label: "category"},
        {id: "e-pkg-list", source: "ListingPackage", target: "Listing", label: "tier of"},
        {id: "e-addon-list", source: "ListingAddOn", target: "Listing", label: "extra on"},
        {id: "e-flag-list", source: "ListingFlag", target: "Listing", label: "flags"},
        {id: "e-promo-list", source: "Promotion", target: "Listing", label: "features"},
        {id: "e-avail-prov", source: "ProviderAvailability", target: "ProviderProfile", label: "schedule"},
        {id: "e-task-cat", source: "TaskRequest", target: "Category", label: "category"},
        {id: "e-bid-task", source: "Bid", target: "TaskRequest", label: "on"},
        {id: "e-mo-list", source: "MarketplaceOrder", target: "Listing", label: "from listing"},
        {id: "e-mo-bid", source: "MarketplaceOrder", target: "Bid", label: "from bid"},
        {id: "e-mo-task", source: "MarketplaceOrder", target: "TaskRequest", label: "awards"},
        {id: "e-mo-prov", source: "MarketplaceOrder", target: "ProviderProfile", label: "provider"},
        {id: "e-book-mo", source: "Booking", target: "MarketplaceOrder", label: "schedules"},
        {id: "e-disp-mo", source: "Dispute", target: "MarketplaceOrder", label: "on"},
        {id: "e-rev-mo", source: "Review", target: "MarketplaceOrder", label: "rates"},
        {
            id: "e-esc-mo",
            source: "EscrowTransaction",
            target: "MarketplaceOrder",
            label: "holds / releases",
            bridge: true,
        },
        {
            id: "e-ms-mo",
            source: "OrderMilestone",
            target: "MarketplaceOrder",
            label: "milestones",
            bridge: true,
        },
        {
            id: "e-od-mo",
            source: "OrderDelivery",
            target: "MarketplaceOrder",
            label: "delivery",
            bridge: true,
        },
        {
            id: "e-or-mo",
            source: "OrderRevision",
            target: "MarketplaceOrder",
            label: "revisions",
            bridge: true,
        },
    ],
    flows: [
        {
            id: "marketplace-listing",
            title: "Buy listing",
            summary:
                "Provider publishes listing (+ packages/add-ons) → buyer purchases → escrow hold → work → delivery/revisions → complete → release + 10% fee → Connect payout.",
            module: "eCommerceMarketplace",
            steps: [
                {
                    id: "ml-profile",
                    label: "Provider profile",
                    description: "Stripe Connect onboarding",
                    detail: "createAccountLink / refreshAccountStatus on ProviderProfile.",
                    position: {x: 0, y: 80},
                },
                {
                    id: "ml-listing",
                    label: "Listing live",
                    description: "Packages + add-ons",
                    detail: "Listing under Category with optional ListingPackage / ListingAddOn.",
                    position: {x: 220, y: 80},
                },
                {
                    id: "ml-order",
                    label: "Create order",
                    description: "createFromListing",
                    detail: "OrderActions.createFromListing computes amount and due date.",
                    position: {x: 440, y: 80},
                },
                {
                    id: "ml-hold",
                    label: "Escrow hold",
                    description: "createEscrowHold",
                    detail: "Funds held via EscrowTransaction (eCommerce bridge).",
                    position: {x: 660, y: 80},
                },
                {
                    id: "ml-work",
                    label: "In progress",
                    description: "accept → start",
                    detail: "Provider accepts and starts the marketplace Order.",
                    position: {x: 880, y: 80},
                },
                {
                    id: "ml-delivery",
                    label: "Delivery",
                    description: "submit → revise (≤3) → accept",
                    detail: "OrderDelivery + OrderRevision cycle until buyer accepts.",
                    position: {x: 1100, y: 80},
                },
                {
                    id: "ml-release",
                    label: "Release + fee",
                    description: "10% platform fee",
                    detail: "createEscrowReleaseAndFee — provider payout + platform fee row.",
                    position: {x: 1320, y: 80},
                },
                {
                    id: "ml-payout",
                    label: "Connect transfer",
                    description: "Stripe Connect",
                    detail: "Transfer to provider stripeAccountId when chargesEnabled.",
                    position: {x: 1540, y: 80},
                },
            ],
            edges: [
                {id: "f-ml-1", source: "ml-profile", target: "ml-listing"},
                {id: "f-ml-2", source: "ml-listing", target: "ml-order"},
                {id: "f-ml-3", source: "ml-order", target: "ml-hold"},
                {id: "f-ml-4", source: "ml-hold", target: "ml-work"},
                {id: "f-ml-5", source: "ml-work", target: "ml-delivery"},
                {id: "f-ml-6", source: "ml-delivery", target: "ml-release"},
                {id: "f-ml-7", source: "ml-release", target: "ml-payout"},
            ],
        },
        {
            id: "marketplace-bid",
            title: "Task + bid",
            summary:
                "Buyer posts TaskRequest → providers Bid → accept bid creates Order → same escrow / delivery / release path as listing purchase.",
            module: "eCommerceMarketplace",
            steps: [
                {
                    id: "mb-task",
                    label: "TaskRequest",
                    description: "Budget + category",
                    detail: "Buyer opens a job with budgetMin/Max under Category.",
                    position: {x: 80, y: 80},
                },
                {
                    id: "mb-bids",
                    label: "Bids",
                    description: "Providers propose",
                    detail: "Multiple Bid documents with amount, proposal, deliveryDays.",
                    position: {x: 360, y: 80},
                },
                {
                    id: "mb-accept",
                    label: "Accept bid",
                    description: "Order created",
                    detail: "Winning bid → Marketplace Order; task awarded/closed.",
                    position: {x: 640, y: 80},
                },
                {
                    id: "mb-escrow",
                    label: "Escrow hold",
                    description: "Same bridge as listing",
                    detail: "createEscrowHold on the new Order.",
                    position: {x: 920, y: 80},
                },
                {
                    id: "mb-complete",
                    label: "Deliver → release",
                    description: "Same lifecycle",
                    detail: "Delivery / revisions / complete → release + 10% fee.",
                    position: {x: 1200, y: 80},
                },
                {
                    id: "mb-dispute",
                    label: "Dispute path",
                    description: "Optional refund",
                    detail: "Dispute can divert to escrow refund instead of release.",
                    position: {x: 920, y: 260},
                },
            ],
            edges: [
                {id: "f-mb-1", source: "mb-task", target: "mb-bids"},
                {id: "f-mb-2", source: "mb-bids", target: "mb-accept"},
                {id: "f-mb-3", source: "mb-accept", target: "mb-escrow"},
                {id: "f-mb-4", source: "mb-escrow", target: "mb-complete"},
                {id: "f-mb-5", source: "mb-escrow", target: "mb-dispute", label: "conflict"},
            ],
        },
    ],
    capabilities: [
        {
            id: "eCommerceMarketplace",
            title: "eCommerce Marketplace",
            summary:
                "P2P / services layer: provider profiles (Stripe Connect), listings with packages & add-ons, task requests & bids, bookings, disputes, reviews — funded through eCommerce escrow.",
            offers: [
                {
                    title: "Provider onboarding",
                    description: "ProviderProfile + availability + Stripe Connect account links.",
                },
                {
                    title: "Listings",
                    description: "Publish offerings with packages, add-ons, promotions, and moderation flags.",
                },
                {
                    title: "Task marketplace",
                    description: "Buyers post TaskRequests; providers Bid; accept creates an Order.",
                },
                {
                    title: "Order lifecycle",
                    description: "Accept → start → deliver → revise → complete / dispute / cancel.",
                },
                {
                    title: "Commission",
                    description: "On escrow release: 10% SERVICE_FEE_PERCENT to platform + Connect transfer to provider.",
                },
            ],
            apis: [
                "/api/eCommerceMarketplace/listing",
                "/api/eCommerceMarketplace/providerProfile",
                "/api/eCommerceMarketplace/taskRequest",
                "/api/eCommerceMarketplace/bid",
                "/api/eCommerceMarketplace/order",
                "/api/eCommerceMarketplace/booking",
                "/api/eCommerceMarketplace/dispute",
                "/api/eCommerceMarketplace/review",
                "/api/eCommerceMarketplace/promotion",
            ],
        },
        {
            id: "shared",
            title: "Escrow bridge (eCommerce)",
            summary:
                "Marketplace Order depends on eCommerce EscrowTransaction, OrderDelivery, OrderMilestone, and OrderRevision. Category taxonomy is also shared.",
            offers: [
                {
                    title: "Shared Category",
                    description: "One taxonomy for Product (catalog), Listing, and TaskRequest.",
                },
                {
                    title: "Escrow hold → release",
                    description: "createEscrowHold on order create; createEscrowReleaseAndFee on completion.",
                },
                {
                    title: "Disputes → refund",
                    description: "Dispute resolution can refund via escrow instead of releasing to provider.",
                },
            ],
            apis: [
                "/api/eCommerceMarketplace/listingCategory",
                "/api/finance/escrowTransaction",
                "/api/eCommerceMarketplace/orderDelivery",
                "/api/eCommerceMarketplace/orderMilestone",
                "/api/eCommerceMarketplace/orderRevision",
            ],
        },
    ],
};
